[user]
name = "Stefan Imhoff"
email = "gpg@kogakure.8shield.net"

[ui]
default-command = "log"
paginate = "never"

[lazyjj]
diff-format = "color-words"

[revsets]
immutable = "main@origin | master@origin"

[signing]
backend = "gpg"
behavior = "own"
key = "7A7253E8!"
