default_startup_script = "~/.config/sesh/scripts/open_files"

[[startup_scripts]]
session_path = "~/Code/GitHub/websites/stefanimhoff-de"
script_path = "~/.config/sesh/scripts/node_dev"

[[session]]
name = "â­Dotfiles"
path = "~/.dotfiles"

[[session]]
name = "ğŸ“¥Downloads"
path = "~/Downloads"
startup_command = "la"

[[session]]
name = "ğŸ“Zettelkasten"
path = "~/Code/GitHub/obsidian/zettelkasten/"

[[session]]
name = "âœ¨Highlights"
path = "~/Code/GitHub/obsidian/highlights/"

[[session]]
name = "ğŸ‘¨â€ğŸ’»stefanimhoff-de"
path = "~/Code/GitHub/websites/stefanimhoff-de/"

[[session]]
name = "ğŸ¥·kogakure-de"
path = "~/Code/GitHub/websites/kogakure-de/"

[[session]]
name = "âš“hamburg-stefanimhoff-de"
path = "~/Code/GitHub/websites/hamburg-stefanimhoff-de/"

[[session]]
name = "ğŸ“¦Crate ğŸŒ³"
path = "~/Code/XING/crate.git/"

[[session]]
name = "ğŸ“¦Crate"
path = "~/Code/XING/crate/"

[[session]]
name = "ğŸºBrewery"
path = "~/Code/XING/crate/xinglets/brewery/"
