config:
  fallback-icon: "?"
  show-name: true

icons:
  bat: "ó°­Ÿ"
  gh: "ï„“"
  nix-env: "ó±„…"
  nix-shell: "ó±„…"
  nix: "ó±„…"
  nvim: "ï¯"
  ollama: "ó°š©"
  opencode: "ó°š©"
  pnpm: "îœ"
  reattach-to-user-namespace: "î¯ˆ"
  spf: "ó°ª¶"
  sudo: "ğŸ”’"
